export const gameBalance = {
  matchDurationMs: 360_000,
  teamSize: 4,
  storageCount: 3,
  acornsPerStorage: 3,
  maxCarryAcorns: 1,
  carrySpeedMultiplier: 0.85,
  arrestHoldMs: 600,
  rescueHoldMs: 3_000,
  rescueArrestImmunityMs: 1_000,
  allJailedConfirmMs: 1_000,
  thunderStunMs: 1_500,
  maxActiveBerries: 2,
  berrySpawnMinMs: 15_000,
  berrySpawnMaxMs: 25_000,
  serverTickRate: 20,
  snapshotRate: 20,
  mapScale: 4,
  mapWidth: 256,
  mapHeight: 192,
  playerSpeed: 7,
  playerRadius: 0.52,
  playerSpawnRadius: 4.5,
  policeSpawnRadius: 3.5,
  interactionRadius: 1.4,
  berryPickupRadius: 0.75,
  berrySpawnRadius: 2.5,
  thunderRange: 15,
  thunderHitRadius: 0.16,
  thunderBeamDurationMs: 180,
  interpolationDelayMs: 100,
  remoteExtrapolationLimitMs: 100,
  reconnectGraceMs: 10_000,
  maxMessageBytes: 8_192,
  maxInputsPerSecond: 60
} as const;

export const totalAcorns = gameBalance.storageCount * gameBalance.acornsPerStorage;
export const fixedDeltaMs = 1_000 / gameBalance.serverTickRate;
