export const gameBalance = {
  matchDurationMs: 360_000,
  teamSize: 4,
  storageCount: 3,
  acornsPerStorage: 3,
  maxCarryAcorns: 1,
  carrySpeedMultiplier: 0.85,
  arrestHoldMs: 900,
  rescueHoldMs: 2_400,
  rescueArrestImmunityMs: 3_600,
  allJailedConfirmMs: 1_000,
  thunderStunMs: 2_250,
  thunderChargeMs: 1_000,
  maxActiveBerries: 6,
  berrySpawnMinMs: 6_000,
  berrySpawnMaxMs: 10_000,
  serverTickRate: 20,
  snapshotRate: 10,
  mapScale: 3,
  mapWidth: 192,
  mapHeight: 144,
  terrainChunkSize: 10,
  playerSpeed: 7,
  playerRadius: 0.52,
  playerSpawnRadius: 4.5,
  policeSpawnRadius: 3.5,
  interactionRadius: 1.4,
  carriedAcornStealRadius: 2.4,
  arrestRadius: 1.75,
  arrestFollowDistance: 1.2,
  berryPickupRadius: 0.75,
  berrySpawnRadius: 2.5,
  treeTarget: 20,
  rockPileTarget: 8,
  bushTarget: 10,
  berrySpawnPointTarget: 28,
  berrySpawnPointMinSeparation: 10.5,
  berryActiveMinSeparation: 9,
  thunderRange: 15,
  thunderHitRadius: 0.16,
  thunderBeamDurationMs: 180,
  interpolationDelayMinMs: 150,
  interpolationDelayMaxMs: 250,
  interpolationJitterMultiplier: 2,
  remoteExtrapolationLimitMs: 100,
  reconnectGraceMs: 10_000,
  botFillDelayMs: 5_000,
  botFillIntervalMs: 1_000,
  botDecisionIntervalMs: 250,
  maxMessageBytes: 8_192,
  maxInputsPerSecond: 60,
  maxChatLength: 120,
  maxChatMessagesPerSecond: 4
} as const;

export const totalAcorns = gameBalance.storageCount * gameBalance.acornsPerStorage;
export const fixedDeltaMs = 1_000 / gameBalance.serverTickRate;
